#test fit config
fitname: "BigGuy_NonCompressed_FullRegions"
asimov: True
datadriven: True

#main fit
#naming convention: Ch#[CR/SR]IDBin where Bin = xy coord in MsRs plane
shape_transfer_fit:
  bin_association:
    Ch1CRGeLep1:
      - "Ch1CRGeLep100"
      - "Ch1CRGeLep110"
      - "Ch1CRGeLep101"
      - "Ch1CRGeLep111"
    Ch2SRGeLep1:
      - "Ch2CRGeLep100"
      - "Ch2SRGeLep110"
      - "Ch2SRGeLep101"
      - "Ch2SRGeLep111"
    Ch3CRGeHad1:
      - "Ch3CRGeHad100"
      - "Ch3CRGeHad110"
      - "Ch3CRGeHad101"
      - "Ch3CRGeHad111"
      - "Ch3CRGeHad121"
    Ch4SRGeHad1:
      - "Ch4CRGeHad100"
      - "Ch4SRGeHad110"
      - "Ch4SRGeHad101"
      - "Ch4SRGeHad111"
      - "Ch4SRGeHad121"
    Ch9CReq1PhoMedIsoPrompt:
      - "Ch9CReq1PhoMedIsoPrompt00"
      - "Ch9CReq1PhoMedIsoPrompt01"
      - "Ch9CReq1PhoMedIsoPrompt10"
      - "Ch9CReq1PhoMedIsoPrompt11"
      - "Ch9CReq1PhoMedIsoPrompt02"
      - "Ch9CReq1PhoMedIsoPrompt12"
    Ch10SReq1PhoTightIsoPrompt:
      - "Ch10CReq1PhoTightIsoPrompt00"
      - "Ch10SReq1PhoTightIsoPrompt01"
      - "Ch10SReq1PhoTightIsoPrompt10"
      - "Ch10SReq1PhoTightIsoPrompt11"
      - "Ch10SReq1PhoTightIsoPrompt02"
      - "Ch10SReq1PhoTightIsoPrompt12"
    Ch11CReq2PhoMedIsoPrompt:
      - "Ch11CReq2PhoMedIsoPrompt00"
      - "Ch11CReq2PhoMedIsoPrompt01"
      - "Ch11CReq2PhoMedIsoPrompt10"
      - "Ch11CReq2PhoMedIsoPrompt11"
    Ch12SReq2PhoTightIsoPrompt:
      - "Ch12CReq2PhoTightIsoPrompt00"
      - "Ch12SReq2PhoTightIsoPrompt01"
      - "Ch12SReq2PhoTightIsoPrompt10"
      - "Ch12SReq2PhoTightIsoPrompt11"
    Ch13CRgeq1SVLowDxygeq1PhoNotBHLate:
      - "Ch13CRgeq1SVLowDxygeq1PhoNotBHLate00"
      - "Ch13CRgeq1SVLowDxygeq1PhoNotBHLate01"
    Ch14SRgeq1SVHighDxygeq1PhoNotBHLate:
      - "Ch14CRgeq1SVHighDxygeq1PhoNotBHLate00"
      - "Ch14SRgeq1SVHighDxygeq1PhoNotBHLate01"
  channel_association:
    Ch1CRGeLep1:
      - "Ch2SRGeLep1"
    Ch3CRGeHad1:
      - "Ch4SRGeHad1"
    Ch9CReq1PhoMedIsoPrompt:
      - "Ch10SReq1PhoTightIsoPrompt"
    Ch11CReq2PhoMedIsoPrompt:
      - "Ch12SReq2PhoTightIsoPrompt"
    Ch13CRgeq1SVLowDxygeq1PhoNotBHLate:
      - "Ch14SRgeq1SVHighDxygeq1PhoNotBHLate"
#main fit
#ABCD - SR bin (D) maps to [C, A, B]
#grid convention
#not bh    C(7) | D(8)
#        ---------
#bh        B(5) | A(6)
#      early -> late
# such that D/A = C/B -> D = C*A/B 
ABCD_fit:
  bin_association:
    Ch5CRgeq1PhoBHEarly:
      - "Ch5CRgeq1PhoBHEarly00"
      - "Ch5CRgeq1PhoBHEarly10"
      - "Ch5CRgeq1PhoBHEarly01"
      - "Ch5CRgeq1PhoBHEarly11"
    Ch6CRgeq1PhoBHLate:
      - "Ch6CRgeq1PhoBHLate00"
      - "Ch6CRgeq1PhoBHLate10"
      - "Ch6CRgeq1PhoBHLate01"
      - "Ch6CRgeq1PhoBHLate11"
    Ch7CRgeq1PhoNotBHEarly:
      - "Ch7CRgeq1PhoNotBHEarly00"
      - "Ch7CRgeq1PhoNotBHEarly10"
      - "Ch7CRgeq1PhoNotBHEarly01"
      - "Ch7CRgeq1PhoNotBHEarly11"
    Ch15CRgeq1PhoMedIsoEarly:
      - "Ch15CRgeq1PhoMedIsoEarly00"
      - "Ch15CRgeq1PhoMedIsoEarly10"
      - "Ch15CRgeq1PhoMedIsoEarly01"
      - "Ch15CRgeq1PhoMedIsoEarly11"
    Ch16CRgeq1PhoMedIsoLate:
      - "Ch16CRgeq1PhoMedIsoLate00"
      - "Ch16CRgeq1PhoMedIsoLate10"
      - "Ch16CRgeq1PhoMedIsoLate01"
      - "Ch16CRgeq1PhoMedIsoLate11"
    Ch17CRgeq1PhoTightIsoEarly: 
      - "Ch17CRgeq1PhoTightIsoEarly00"
      - "Ch17CRgeq1PhoTightIsoEarly10"
      - "Ch17CRgeq1PhoTightIsoEarly01"
      - "Ch17CRgeq1PhoTightIsoEarly11"
    Ch8SRgeq1PhoNotBHLateTightIso:
      - "Ch8SRgeq1PhoNotBHLateTightIso00"
      - "Ch8SRgeq1PhoNotBHLateTightIso10"
      - "Ch8SRgeq1PhoNotBHLateTightIso01"
      - "Ch8SRgeq1PhoNotBHLateTightIso11"
  channel_association:
    Ch8SRgeq1PhoNotBHLateTightIso:
      bkgbh:
        - "Ch6CRgeq1PhoBHLate"
        - "Ch7CRgeq1PhoNotBHEarly"
        - "Ch5CRgeq1PhoBHEarly"
      bkgprompt:
        - "Ch16CRgeq1PhoMedIsoLate"
        - "Ch17CRgeq1PhoTightIsoEarly"
        - "Ch15CRgeq1PhoMedIsoEarly"
  #can add channel associations for stacked ABCD fits
#extra systematics
systematics:
  #sys0:
  #    type: "lnN"
  #    name: "scale_Ch7CRgeq1PhoNotBHEarly11"
  #    init_val: 1.05
  #    procs:
  #      - "bkgbh"
  #    bins:
  #      - "Ch7CRgeq1PhoNotBHEarly11"

  #pin CR channels
  sys1:
      type: "lnN"
      name: "lnN_Ch1Ch2geLep1Shape00"
      init_val: 1.05
      bins:
        - "Ch1CRgeLep100"
        - "Ch2CRgeLep100"
  sys2:
      type: "lnN"
      name: "lnN_Ch1Ch2geLep1Shape01"
      init_val: 1.05
      bins:
        - "Ch1CRgeLep101"
        - "Ch2SRgeLep101"
  sys3:
      type: "lnN"
      name: "lnN_Ch1Ch2geLep1Shape10"
      init_val: 1.05
      bins:
        - "Ch1CRgeLep110"
        - "Ch2SRgeLep110"
  sys4:
      type: "lnN"
      name: "lnN_Ch1Ch2geLep1Shape11"
      init_val: 1.05
      bins:
        - "Ch1CRgeLep111"
        - "Ch2SRgeLep111"
  sys5:
      type: "lnN"
      name: "lnN_Ch1geLep1Shape00"
      init_val: 1.05
      bins:
        - "Ch1CRgeLep100"
  sys6:
      type: "lnN"
      name: "lnN_Ch3Ch4geHad1Shape00"
      init_val: 1.05
      bins:
        - "Ch3CRgeHad100"
        - "Ch4CRgeHad100"
  sys7:
      type: "lnN"
      name: "lnN_Ch3Ch4geHad1Shape01"
      init_val: 1.05
      bins:
        - "Ch3CRgeHad101"
        - "Ch4SRgeHad101"
  sys8:
      type: "lnN"
      name: "lnN_Ch3Ch4geHad1Shape10"
      init_val: 1.05
      bins:
        - "Ch3CRgeHad110"
        - "Ch4SRgeHad110"
  sys9:
      type: "lnN"
      name: "lnN_Ch3Ch4geHad1Shape11"
      init_val: 1.05
      bins:
        - "Ch3CRgeHad111"
        - "Ch4SRgeHad111"
  sys10:
      type: "lnN"
      name: "lnN_Ch3Ch4geHad1Shape21"
      init_val: 1.05
      bins:
        - "Ch3CRgeHad121"
        - "Ch4SRgeHad121"
  sys11:
      type: "lnN"
      name: "lnN_Ch3geHad1Shape00"
      init_val: 1.05
      bins:
        - "Ch3CRgeHad100"
  #sys12:
  #  type: "lnN"
  #  name: "scale_Ch5CRgeq1PhoBHEarly00"
  #  init_val: 1.05
  #  bins:
  #    - "Ch5CRgeq1PhoBHEarly00"
  #sys13:
  #  type: "lnN"
  #  name: "scale_Ch6CRgeq1PhoBHLate00"
  #  init_val: 1.05
  #  bins:
  #    - "Ch6CRgeq1PhoBHLate00"
  #sys14:
  #  type: "lnN"
  #  name: "scale_Ch7CRgeq1PhoNotBHEarly00"
  #  init_val: 1.05
  #  bins:
  #    - "Ch7CRgeq1PhoNotBHEarly00"
  sys15:
      type: "lnN"
      name: "lnN_Ch9Ch10eq1Shape00"
      init_val: 1.05
      bins:
          - "Ch9CReq1PhoMedIsoPrompt00"
          - "Ch10CReq1PhoTightIsoPrompt00"
  sys16:
      type: "lnN"
      name: "lnN_Ch9Ch10eq1Shape01"
      init_val: 1.1
      bins:
          - "Ch9CReq1PhoMedIsoPrompt01"
          - "Ch10SReq1PhoTightIsoPrompt01"
  sys17:
      type: "lnN"
      name: "lnN_Ch9Ch10eq1Shape02"
      init_val: 1.1
      bins:
          - "Ch9CReq1PhoMedIsoPrompt02"
          - "Ch10SReq1PhoTightIsoPrompt02"
  sys18:
      type: "lnN"
      name: "lnN_Ch9Ch10eq1Shape10"
      init_val: 1.1
      bins:
          - "Ch9CReq1PhoMedIsoPrompt10"
          - "Ch10SReq1PhoTightIsoPrompt10"
  sys19:
      type: "lnN"
      name: "lnN_Ch9Ch10eq1Shape11"
      init_val: 1.15 
      bins:
          - "Ch9CReq1PhoMedIsoPrompt11"
          - "Ch10SReq1PhoTightIsoPrompt11"
  sys20:
      type: "lnN"
      name: "lnN_Ch9Ch10eq1Shape12"
      init_val: 1.15 
      bins:
          - "Ch9CReq1PhoMedIsoPrompt12"
          - "Ch10SReq1PhoTightIsoPrompt12"
  sys21:
      type: "lnN"
      name: "lnN_Ch9eq1Shape00"
      init_val: 1.1 
      bins:
          - "Ch9CReq1PhoMedIsoPrompt00"
  sys22:
      type: "lnN"
      name: "lnN_Ch11Ch12eq2Shape00"
      init_val: 1.1 
      bins:
          - "Ch12CReq2PhoMedIsoPrompt00"
          - "Ch11CReq2PhoTightIsoPrompt00"
  sys23:
      type: "lnN"
      name: "lnN_Ch11Ch12eq2Shape01"
      init_val: 1.1 
      bins:
          - "Ch11CReq2PhoMedIsoPrompt01"
          - "Ch12SReq2PhoTightIsoPrompt01"
  sys24:
      type: "lnN"
      name: "lnN_Ch11Ch12eq2Shape10"
      init_val: 1.1 
      bins:
          - "Ch11CReq2PhoMedIsoPrompt10"
          - "Ch12SReq2PhoTightIsoPrompt10"
  sys25:
      type: "lnN"
      name: "lnN_Ch11Ch12eq2Shape11"
      init_val: 1.05
      bins:
          - "Ch11CReq2PhoMedIsoPrompt11"
          - "Ch12SReq2PhoTightIsoPrompt11"
  sys26:
      type: "lnN"
      name: "lnN_Ch12eq2Shape00"
      init_val: 1.1 
      bins:
          - "Ch12CReq2PhoMedIsoPrompt00"
  sys27:
      type: "lnN"
      name: "lnN_SignalSyst"
      init_val: 1.1 
      procs:
          - "sig"
