analysis:
  name: "Batch_Test_1"
  luminosity: 400.0
  output_json: "batch_test_1.json"

samples:
  backgrounds: ["Wjets", "Zjets"]
  signals: ["gogoG"]

bins:
  test_bin_1:
    description: "First batch test bin"
    cuts:
      - "nSelPhotons >= 1"
      - "rjr_Mr[1] > 1000"